### ISSUE TITLE
Fix the Conduit application to add multiple Conduits 

### ISSUE THREAD

**Issue by kavithaii** [million-views/praas#54] opened 2020-05-04 08:29 UTC
After creating my first Conduit, when I try to add one more Conduit, new conduit is not getting created.

1. I clicked the Create Conduit button.
2. Then started filling the Create Conduit form, 
3. added the API key, 
4. selected the Smart sheets, 
5. added spreadsheet URL, 
6. checked the required Request access, 
7. added Description of end point, 
9. at last Clicked the Create Conduit button, no action.

**Comment by m5nv** [comment] 2020-07-22 09:36
Duplicate of #53.

**Closed by m5nv** 2020-07-22 09:36 UTC
Labels: bug, good first issue
